### ISSUE TITLE
Quoting on:click events

### ISSUE THREAD

**Issue by ppedrazzi** [laosb/SvelteNova#8] opened 2021-05-29 15:33 UTC
Not an issue, but wondering about double quoting as the approach for things like on:click or class:foo?  I've used svelte without it and it seems fine without the quotes, but maybe I'm off here.

Challenge with quoting is you lose all syntax formatting.  

See example.
<img width="341" alt="CleanShot 2021-05-29 at 08 29 34@2x" src="https://user-images.githubusercontent.com/587780/120075977-5cb5b780-c058-11eb-80d0-7a1a831f5c29.png">

**Comment by laosb** [comment] 2021-08-06 04:24
In Svelte docs they do it without quotes. That looks more accurate to me and is how I do this. If the syntax highlights looks wrong, I'm sorry but I'm not capable enough to fix. I'm closing this since this is not a bug report. Please don't hesitate to report as a bug if it is.

**Closed as completed by laosb** 2021-08-06 04:24 UTC
